# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x08messages\"\x13\n\x11PingServerRequest\"\x11\n\x0fPingServerReply\"\x12\n\x10GetIpListRequest\"!\n\x0eGetIpListReply\x12\x0f\n\x07ip_list\x18\x01 \x03(\t\"\x1b\n\x19InitiateConnectionRequest\"\x19\n\x17InitiateConnectionReply2\xf9\x01\n\x06Server\x12G\n\x0bping_server\x12\x1b.messages.PingServerRequest\x1a\x19.messages.PingServerReply\"\x00\x12\x45\n\x0bget_ip_list\x12\x1a.messages.GetIpListRequest\x1a\x18.messages.GetIpListReply\"\x00\x12_\n\x13initiate_connection\x12#.messages.InitiateConnectionRequest\x1a!.messages.InitiateConnectionReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PINGSERVERREQUEST._serialized_start=26
  _PINGSERVERREQUEST._serialized_end=45
  _PINGSERVERREPLY._serialized_start=47
  _PINGSERVERREPLY._serialized_end=64
  _GETIPLISTREQUEST._serialized_start=66
  _GETIPLISTREQUEST._serialized_end=84
  _GETIPLISTREPLY._serialized_start=86
  _GETIPLISTREPLY._serialized_end=119
  _INITIATECONNECTIONREQUEST._serialized_start=121
  _INITIATECONNECTIONREQUEST._serialized_end=148
  _INITIATECONNECTIONREPLY._serialized_start=150
  _INITIATECONNECTIONREPLY._serialized_end=175
  _SERVER._serialized_start=178
  _SERVER._serialized_end=427
# @@protoc_insertion_point(module_scope)
